# Generated by Django 5.0.6 on 2024-08-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chanakya', '0002_alter_conversationmodel_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='aliases',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='request_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='period_type',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='transaction_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='type',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
