# Generated by Django 5.0.6 on 2024-08-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chanakya', '0003_remove_usersubscription_aliases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='subscription_expire',
            field=models.BooleanField(default=False),
        ),
    ]
