# Generated by Django 5.0.6 on 2024-08-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chanakya', '0004_usersubscription_subscription_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptsmodel',
            name='assistant_token',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='promptsmodel',
            name='begin_of_text_token',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='promptsmodel',
            name='end_token',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='promptsmodel',
            name='eot_token',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='promptsmodel',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='promptsmodel',
            name='start_token',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='promptsmodel',
            name='system_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='promptsmodel',
            name='system_token',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='promptsmodel',
            name='user_token',
            field=models.TextField(blank=True),
        ),
    ]
