# Generated by Django 5.1 on 2024-08-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chanakya', '0005_alter_promptsmodel_assistant_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptsmodel',
            name='assistant_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promptsmodel',
            name='begin_of_text_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promptsmodel',
            name='end_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promptsmodel',
            name='eot_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promptsmodel',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promptsmodel',
            name='start_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promptsmodel',
            name='system_message',
            field=models.CharField(blank=True, max_length=8000),
        ),
        migrations.AlterField(
            model_name='promptsmodel',
            name='system_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promptsmodel',
            name='user_token',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
